# Generated by Django 2.1.2 on 2018-10-17 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Название препарата')),
                ('photo', models.FileField(upload_to='', verbose_name='Фото')),
                ('price', models.PositiveSmallIntegerField(verbose_name='Цена')),
                ('category', models.IntegerField(choices=[(0, 'Пусто'), (1, 'Для носа'), (2, 'Для горла')], default=0, verbose_name='Категория')),
                ('expiration_date', models.DateTimeField(null=True)),
                ('status', models.BooleanField(default=True, verbose_name='Активен')),
                ('comment', models.CharField(max_length=500, verbose_name='Комментарий')),
            ],
        ),
    ]
