# Generated by Django 2.1.2 on 2018-10-18 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymedicaments', '0002_auto_20181018_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicament',
            name='category',
            field=models.IntegerField(choices=[(0, 'Пусто'), (1, 'Для носа'), (2, 'Для горла'), (3, 'Витамины'), (4, 'БАДы')], default=0, verbose_name='Категория'),
        ),
    ]
