# Generated by Django 2.1.2 on 2018-10-18 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymedicaments', '0003_auto_20181018_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicament',
            name='expiration_date',
            field=models.DateField(null=True),
        ),
    ]
