# Generated by Django 2.1.2 on 2018-10-18 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymedicaments', '0004_auto_20181018_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicament',
            name='photo',
            field=models.FileField(null=True, upload_to='', verbose_name='Фото'),
        ),
    ]
