# Generated by Django 2.1.2 on 2018-10-18 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymedicaments', '0005_auto_20181018_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicament',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Фото'),
        ),
    ]
