# Generated by Django 2.1.2 on 2018-10-18 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymedicaments', '0006_auto_20181018_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicament',
            name='comment',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Комментарий'),
        ),
    ]
