# Generated by Django 2.1.2 on 2018-10-29 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymedicaments', '0007_auto_20181018_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicament',
            name='photo_date',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Фото дат на упаковке'),
        ),
        migrations.AddField(
            model_name='medicament',
            name='photo_recipe',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Фото рецепта'),
        ),
    ]
