# Generated by Django 2.1.2 on 2018-10-29 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymedicaments', '0008_auto_20181029_2034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicament',
            name='photo',
        ),
        migrations.AddField(
            model_name='medicament',
            name='photo_face',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Фото упаковки'),
        ),
    ]
