# Generated by Django 2.1.2 on 2018-10-29 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymedicaments', '0009_auto_20181029_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicament',
            name='status',
            field=models.IntegerField(choices=[(0, 'Активен'), (1, 'Израсходован'), (2, 'Удалён')], default=0, verbose_name='Статус'),
        ),
    ]
