# Generated by Django 2.1.2 on 2018-11-03 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mymedicaments', '0010_auto_20181029_2046'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Категория препарата')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Категория препарата')),
            ],
        ),
        migrations.AlterField(
            model_name='medicament',
            name='category',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='mymedicaments.Category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='medicament',
            name='expiration_date',
            field=models.DateField(blank=True, null=True, verbose_name='Годен до'),
        ),
        migrations.AlterField(
            model_name='medicament',
            name='status',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='mymedicaments.Status', verbose_name='Статус'),
        ),
    ]
