# Generated by Django 2.1.2 on 2018-11-03 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mymedicaments', '0012_auto_20181103_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicament',
            name='category',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='mymedicaments.Category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='medicament',
            name='status',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='mymedicaments.Status', verbose_name='Статус'),
        ),
    ]
