# Generated by Django 2.1.2 on 2018-11-13 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymedicaments', '0016_auto_20181111_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicament',
            name='name',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Название препарата'),
        ),
        migrations.AlterField(
            model_name='medicament',
            name='price',
            field=models.FloatField(blank=True, null=True, verbose_name='Цена'),
        ),
    ]
