# Generated by Django 2.1.2 on 2018-12-09 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymedicaments', '0017_auto_20181113_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicament',
            name='photo_date_medium',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Фото дат на упаковке средний'),
        ),
        migrations.AddField(
            model_name='medicament',
            name='photo_date_small',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Фото дат на упаковке малый'),
        ),
        migrations.AddField(
            model_name='medicament',
            name='photo_face_medium',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Фото упаковки средний'),
        ),
        migrations.AddField(
            model_name='medicament',
            name='photo_face_small',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Фото упаковки малый'),
        ),
        migrations.AddField(
            model_name='medicament',
            name='photo_recipe_medium',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Фото рецепта средний'),
        ),
        migrations.AddField(
            model_name='medicament',
            name='photo_recipe_small',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Фото рецепта малый'),
        ),
        migrations.AlterField(
            model_name='medicament',
            name='photo_date',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Фото дат на упаковке оригинальный'),
        ),
        migrations.AlterField(
            model_name='medicament',
            name='photo_face',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Фото упаковки оригинальный'),
        ),
        migrations.AlterField(
            model_name='medicament',
            name='photo_recipe',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Фото рецепта оригинальный'),
        ),
    ]
